modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "rallyguard"
version = "${version}"
displayName = "Rally of the Guard - Forge"
authors = "Hyan Ferreira (hfstack)"
description = '''
Hire, command, patrol, and rally Guard Villagers on Forge without requiring Hero of the Village.
'''
#logoFile = ""

[[dependencies.rallyguard]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rallyguard]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rallyguard]]
modId = "guardvillagers"
mandatory = true
versionRange = "[1.6.18,)"
ordering = "AFTER"
side = "BOTH"
