modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "rallyguard"
version = "${version}"
displayName = "Rally of the Guard - FORGE"
authors = "Hyan Ferreira (hfstack)"
description = '''
Em breve esccrevo algo
'''
#logoFile = ""

[[dependencies.rallyguard]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rallyguard]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rallyguard]]
modId = "guardvillagers"
mandatory = true
versionRange = "[1.6.18,)"
ordering = "AFTER"
side = "BOTH"
